# This file only provides the secrets for the development environment.
# The production environment secrets filed gets copied in during deploy.

development:
  aws_access_key_id: AKIAIMZCAT3NQGE7E6OA
  aws_secret_access_key: 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
  aws_region: eu-west-1
  aws_queue_suffix: -development
  application_name: test_runner_orchestrator_dev
  aws_iterations_bucket: exercism-iterations

test:
  aws_access_key_id: CHANGE_ME
  aws_secret_access_key: CHANGE_ME
  aws_region: eu-west-1
  aws_queue_suffix: -test
  application_name: test_runner_orchestrator_test
  aws_iterations_bucket: test-exercism-iterations
